name: 'Hello World'
description: 'greet action'
inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: 'World'
  random-number:
    description: 'number'
    required: true
    default: 1
outputs:
  time:
    description: 'the time we greeted you'
  name:
    description: 'random name that we pass back to you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.random-number }}
