name: 'Hello World'
description: 'CSV Action'
inputs:
  csv-file:
    description: 'csv you want anaylzed'
    required: true
    default: 'default.csv'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.csv-file }}
